"""Train a small temporal head on FireRed AED probabilities.

Input is the `probs` NPZ generated by `evaluate_firered_aed_sample.py`, not raw
audio. The exported ONNX is intended as the next upgrade path after hard-coded
rules.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import torch
from torch import nn

from evaluate_firered_aed_sample import build_half_second_stats, build_labels, load_annotations, metrics

HOP_SEC = 0.5


def causal_mean(values: np.ndarray, window_steps: int) -> np.ndarray:
    window_steps = max(1, int(window_steps))
    csum = np.concatenate([[0.0], np.cumsum(values, dtype=np.float64)])
    out = np.empty_like(values, dtype=np.float32)
    for i in range(len(values)):
        start = max(0, i + 1 - window_steps)
        out[i] = (csum[i + 1] - csum[start]) / max(1, i + 1 - start)
    return out


def causal_max(values: np.ndarray, window_steps: int) -> np.ndarray:
    window_steps = max(1, int(window_steps))
    out = np.empty_like(values, dtype=np.float32)
    for i in range(len(values)):
        start = max(0, i + 1 - window_steps)
        out[i] = np.max(values[start:i + 1])
    return out


def time_since(values: np.ndarray, threshold: float) -> np.ndarray:
    out = np.empty(len(values), dtype=np.float32)
    last = None
    for i, value in enumerate(values):
        if value >= threshold:
            last = i
            out[i] = 0.0
        elif last is None:
            out[i] = 120.0
        else:
            out[i] = min(120.0, (i - last) * HOP_SEC)
    return out / 120.0


def build_temporal_features(stats: Dict[str, np.ndarray]) -> Tuple[np.ndarray, List[str]]:
    feature_arrays = []
    names = []

    def add(name: str, values: np.ndarray) -> None:
        feature_arrays.append(values.astype(np.float32))
        names.append(name)

    base_keys = [
        "speech_max",
        "singing_max",
        "music_max",
        "speech_mean",
        "singing_mean",
        "music_mean",
        "speech_ratio",
        "singing_ratio",
        "music_ratio",
    ]
    for key in base_keys:
        add(key, stats[key])

    for sec in [4, 10, 30]:
        steps = round(sec / HOP_SEC)
        for key in ["speech_max", "singing_max", "music_max", "speech_mean", "singing_mean", "music_mean"]:
            add(f"{key}_mean_{sec}s", causal_mean(stats[key], steps))
        add(f"singing_max_peak_{sec}s", causal_max(stats["singing_max"], steps))
        add(f"speech_max_peak_{sec}s", causal_max(stats["speech_max"], steps))

    add("time_since_singing_0_78", time_since(stats["singing_max"], 0.78))
    add("time_since_singing_0_90", time_since(stats["singing_max"], 0.90))
    add(
        "music_minus_speech_10s",
        causal_mean(stats["music_mean"], round(10 / HOP_SEC)) - causal_mean(stats["speech_mean"], round(10 / HOP_SEC)),
    )
    add(
        "singing_minus_speech_10s",
        causal_mean(stats["singing_mean"], round(10 / HOP_SEC)) - causal_mean(stats["speech_mean"], round(10 / HOP_SEC)),
    )

    return np.stack(feature_arrays, axis=1).astype(np.float32), names


class TemporalHead(nn.Module):
    def __init__(self, input_dim: int, hidden_dim: int = 32) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.sigmoid(self.net(x)).squeeze(-1)


def find_best_threshold(probs: np.ndarray, labels: np.ndarray, beta: float = 0.5) -> Tuple[float, Dict[str, float]]:
    best_thr = 0.5
    best_metrics: Dict[str, float] = {}
    best_score = -1.0
    beta2 = beta * beta
    for thr in np.linspace(0.05, 0.95, 181):
        pred = (probs >= thr).astype(np.int8)
        m = metrics(pred, labels)
        score = (1 + beta2) * m["precision"] * m["recall"] / max(1e-9, beta2 * m["precision"] + m["recall"])
        if score > best_score:
            best_score = score
            best_thr = float(thr)
            best_metrics = m
    return best_thr, best_metrics


def split_by_time(n: int, val_fraction: float) -> Tuple[np.ndarray, np.ndarray]:
    split = max(1, min(n - 1, int(n * (1.0 - val_fraction))))
    return np.arange(split), np.arange(split, n)


def train(args: argparse.Namespace) -> None:
    probs = np.load(args.probs)["probs"]
    stats = build_half_second_stats(probs)
    labels = build_labels(stats["time"], load_annotations(args.annotations)).astype(np.float32)
    x, feature_names = build_temporal_features(stats)

    train_idx, val_idx = split_by_time(len(x), args.val_fraction)
    x_train = torch.from_numpy(x[train_idx])
    y_train = torch.from_numpy(labels[train_idx])
    x_val = torch.from_numpy(x[val_idx])
    y_val_np = labels[val_idx].astype(np.int8)

    model = TemporalHead(x.shape[1], args.hidden_dim)
    pos = float((labels[train_idx] == 1).sum())
    neg = float((labels[train_idx] == 0).sum())
    pos_weight = torch.tensor([neg / max(1.0, pos)], dtype=torch.float32)
    loss_fn = nn.BCELoss(reduction="none")
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    best_state = None
    best_score = -1.0
    best_thr = 0.5
    best_metrics: Dict[str, float] = {}

    for epoch in range(1, args.epochs + 1):
        model.train()
        optimizer.zero_grad(set_to_none=True)
        pred = model(x_train)
        weights = torch.where(y_train > 0.5, pos_weight, torch.ones_like(y_train))
        loss = (loss_fn(pred, y_train) * weights).mean()
        loss.backward()
        optimizer.step()

        if epoch % args.eval_every == 0 or epoch == args.epochs:
            model.eval()
            with torch.no_grad():
                val_probs = model(x_val).cpu().numpy()
            thr, m = find_best_threshold(val_probs, y_val_np, beta=args.beta)
            score = m.get("f0_5", m.get("f1", 0.0))
            if score > best_score:
                best_score = score
                best_thr = thr
                best_metrics = m
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            print(
                f"epoch={epoch:04d} loss={loss.item():.5f} thr={thr:.3f} "
                f"precision={m['precision']:.4f} recall={m['recall']:.4f} f1={m['f1']:.4f}"
            )

    if best_state is not None:
        model.load_state_dict(best_state)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), args.out_dir / "firered_temporal_head.pt")

    onnx_path = args.out_dir / "firered_temporal_head.onnx"
    dummy = torch.zeros(1, x.shape[1], dtype=torch.float32)
    torch.onnx.export(
        model,
        dummy,
        str(onnx_path),
        input_names=["temporal_features"],
        output_names=["song_probability"],
        dynamic_axes={"temporal_features": {0: "batch"}, "song_probability": {0: "batch"}},
        opset_version=17,
        do_constant_folding=True,
    )

    meta = {
        "modelType": "firered-temporal-head",
        "detectorVersion": "firered-aed-temporal-head-v1",
        "inputName": "temporal_features",
        "outputName": "song_probability",
        "inputDim": len(feature_names),
        "featureNames": feature_names,
        "threshold": best_thr,
        "bestValMetrics": best_metrics,
        "hopSec": HOP_SEC,
        "notes": "Features are causal aggregates from FireRed AED speech/singing/music probabilities.",
    }
    (args.out_dir / "firered_temporal_head.meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"[done] wrote {onnx_path}")
    print(json.dumps({"threshold": best_thr, "metrics": best_metrics}, ensure_ascii=False, indent=2))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--probs", type=Path, required=True, help="NPZ generated by evaluate_firered_aed_sample.py.")
    parser.add_argument("--annotations", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=Path("training_runs/firered_temporal_head"))
    parser.add_argument("--epochs", type=int, default=300)
    parser.add_argument("--eval-every", type=int, default=20)
    parser.add_argument("--hidden-dim", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--val-fraction", type=float, default=0.2)
    parser.add_argument("--beta", type=float, default=0.5, help="F-beta beta; 0.5 emphasizes precision.")
    return parser.parse_args()


if __name__ == "__main__":
    train(parse_args())
